window.pdfFiles = window.pdfFiles = [
    "115_Java_Interview_Questions_and 13923.pdf",
    "Advanced Topics in Java 13926.pdf",
    "API testing.pdf",
    "Beginning Apache Struts 13933.pdf",
    "Beginning Java Programming For Dummies@englishbooks 49084.pdf",
    "Beginning Java Programming 13934.pdf",
    "Building Mobile Applications with Java 13937.pdf",
    "cicd1.pdf",
    "Core-Servlets-and-JSP 13938.pdf",
    "Data Structures and Algorithms in Java, 6th Edition 13939.pdf",
    "Developing_RESTful_Services_with 13940.pdf",
    "From+Java+Dev+to+AI+Engineer-+Spring+AI+Fast+Track+-+Print.pdf",
    "Functional Programming in Java 13946.pdf",
    "Java Collection Matrix 14155.pdf",
    "Java EE 7 Performance Tuning and Optimization 13961.pdf",
    "Java EE 7 The Big Picture 13962.pdf",
    "Java For Dummies 4th Ed Dec 2006@englishbooks 49228.pdf",
    "Java Generics and Collections 13965.pdf",
    "Java How to Program, 10th Edition 13967.pdf",
    "Java Interview Questions and Answers 15223.pdf",
    "Java Message Service, 2nd Edition 13968.pdf",
    "Java Programming Interviews Exposed 13973.pdf",
    "Java Servlet Programming 13976.pdf",
    "Java Web Services Up and Running, 2nd Edition 13977.pdf",
    "Java 8 Lambdas 13958.pdf",
    "Java 8 Pocket Guide 13959.pdf",
    "Java-J2EE JOB Interview Companion 14160.pdf",
    "JavaInterviewQuestions.pdf",
    "javaQuestions.pdf",
    "js1.pdf",
    "JWT.pdf",
    "Microservice.pdf",
    "MongoDB for Java Developers 13991.pdf",
    "Objects First with Java, 5th Edition 13992.pdf",
    "OCA Java SE 7 Programmer I Certification Guide 13993.pdf",
    "Oracle Certified Associate, Java SE 7 Programmer Study Guide 13998.pdf",
    "Oracle_Certified_Professional_Java 13999.pdf",
    "springboot1.pdf",
    "springBoot2.pdf",
    "SpringbootToDocker.pdf",
    "Wireless Hacking.pdf",
    "𝑪𝒐𝒓𝒆_𝑱𝒂𝒗𝒂_𝑪𝒉𝒆𝒂𝒕_𝒔𝒉𝒆𝒆𝒕_.pdf"
];
